solveNaive: solveNaive.c Period.h
	clang solveNaive.c -o solveNaive 

solveSmart: solveSmart.c Period.h
	clang solveSmart.c -o solveSmart 

timeNaive: timeNaive.c Period.h
	clang timeNaive.c -o timeNaive -lm

timeSmart: timeSmart.c Period.h
	clang timeSmart.c -o timeSmart -lm
